#cloud-config
package_update: true
package_upgrade: true
packages:
  - python3
  - python3-pip
  - python3-venv
  - git

runcmd:
  - systemctl stop apparmor.service || true
  - systemctl disable apparmor.service || true
  - '[ ! -d /opt/rabbit ] && git clone https://github.com/fibrafacil/rabbit.git /opt/rabbit || (cd /opt/rabbit && git pull)'
  - python3 -m venv /opt/rabbit/venv
  - /opt/rabbit/venv/bin/pip install --upgrade pip
  - /opt/rabbit/venv/bin/pip install flask
  - |
    cat << EOF > /etc/systemd/system/rabbit.service
    [Unit]
    Description=Rabbit Dashboard Backend
    After=network.target

    [Service]
    ExecStart=/opt/rabbit/venv/bin/python /opt/rabbit/backend/app.py
    WorkingDirectory=/opt/rabbit
    Restart=always
    User=root

    [Install]
    WantedBy=multi-user.target
    EOF
  - systemctl daemon-reload
  - systemctl enable rabbit
  - systemctl start rabbit
